### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by kristopherjturner** [bottkars/pks-jump-azure#2]
So my deployment makes it past the installation of Opsman and Bosh Director.  In the logs everything looks good up to Task 6 which shows completed successful.  The next step looks like it maybe having issues communicating to the api?  Some timeouts?

Status: 404 Not Found
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Mon, 21 Jan 2019 00:54:48 GMT
Server: Ops Manager
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Request-Id: 51a144d7-d426-4716-bb1a-ee148125cbb7
X-Runtime: 0.001245
could not execute "curl": server responded with an error
failed to access https://api.pkssandbox.countrycloudboy.com:8443: http timeout
uaac error
OptionParser::MissingArgument: missing argument: -s

The logs do show that it is creating the K8SCLUSTER.  The last thing I see that it creates is the A record in the DNS Zone.  Then it starts throwing errors that you must be logged on and are not currently authenticated.

**Comment by bottkars** [comment]
Thynks for bringing that up.
Task 6 is just finishing Opsman Deployment . From there , PKS deployment takes another 20 Steps.

DO you use a different ADMIN_USERNAME than the default UBUNTU ? then most likely a su calls will fail


if that is the case, i will prepare a fix by tonight
